site_name: AlphaNord's Notes
site_url: https://alphanord.github.io/

theme:
  name: material
  palette:
    scheme: slate          # dark mode
    primary: indigo
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy

plugins:
  - search
  - blog                   # built-in blog plugin (Material only)

markdown_extensions:
  - pymdownx.arithmatex:   # LaTeX math support (great for EE)
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
