site_name: AlphaNord's Notes
site_url: https://alphanord.github.io/

theme:
  name: material
  font: false
  icon:
    logo: fontawesome/solid/compass-drafting
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy

plugins:
  - search
  - blog # built-in blog plugin (Material only)

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex: # LaTeX math support (great for EE)
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
